const BACKENDS = Object.freeze({
  OATH_CLAUDE: 'OATH_CLAUDE',
  ANTHROPIC_CLAUDE_API: 'ANTHROPIC_CLAUDE_API',
  LITELLM_PROXY: 'LITELLM_PROXY',
  LOCAL_QWEN: 'LOCAL_QWEN',
  LOCAL_OLLAMA: 'LOCAL_OLLAMA',
  LOCAL_OPENAI_COMPAT: 'LOCAL_OPENAI_COMPAT'
});

const TASK_CLASSES = Object.freeze({
  BASIC: 'BASIC',
  NON_BASIC: 'NON_BASIC'
});

const ERROR_CODES = Object.freeze({
  AUTH: 'AUTH',
  RATE_LIMIT: 'RATE_LIMIT',
  QUOTA: 'QUOTA',
  TIMEOUT: 'TIMEOUT',
  CONTEXT: 'CONTEXT',
  NETWORK: 'NETWORK',
  UNKNOWN: 'UNKNOWN',
  NONE: 'NONE'
});

module.exports = {
  BACKENDS,
  TASK_CLASSES,
  ERROR_CODES
};
