#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HIVE_DIR = REPO_ROOT / "workspace" / "hivemind" / "hivemind"
OUT_PATH = REPO_ROOT / "workspace" / "hivemind" / "WIRING_STATUS.md"

FLAG_MAP = {
    "peer_graph": "ENABLE_MURMURATION",
    "reservoir": "ENABLE_RESERVOIR",
    "physarum_router": "ENABLE_PHYSARUM_ROUTER",
    "trails": "ENABLE_TRAIL_MEMORY",
    "active_inference": "OPENCLAW_COUNTERFACTUAL_REPLAY",
}


def _enabled(name: str) -> bool:
    return str(os.environ.get(name, "0")).strip().lower() in {"1", "true", "yes", "on"}


def _status(module: str, wired_modules: set[str]) -> str:
    flag = FLAG_MAP.get(module)
    if flag and _enabled(flag):
        return "active"
    if module in wired_modules:
        return "wired but passive"
    return "decorative"


def _wired_modules() -> set[str]:
    wired = set()
    for rel in [
        REPO_ROOT / "workspace" / "hivemind" / "hivemind" / "dynamics_pipeline.py",
        REPO_ROOT / "workspace" / "hivemind" / "hivemind" / "integrations" / "main_flow_hook.py",
    ]:
        txt = rel.read_text(encoding="utf-8") if rel.exists() else ""
        for py in HIVE_DIR.glob("*.py"):
            name = py.stem
            if name == "__init__":
                continue
            if name in txt:
                wired.add(name)
    return wired


def generate(out_path: Path) -> str:
    modules = sorted(py.stem for py in HIVE_DIR.glob("*.py") if py.stem != "__init__")
    wired = _wired_modules()
    date_utc = datetime.now(UTC).date().isoformat()

    lines = [
        "# Hivemind Wiring Status",
        "",
        "Generated by workspace/scripts/generate_wiring_status.py",
        "",
        "| module | status | last_verified_utc |",
        "|---|---|---|",
    ]
    for module in modules:
        lines.append(f"| {module} | {_status(module, wired)} | {date_utc} |")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return str(out_path.relative_to(REPO_ROOT))


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate hivemind wiring status table")
    parser.add_argument("--output", default=str(OUT_PATH))
    args = parser.parse_args()
    rel = generate(Path(args.output))
    print(rel)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
